# Generated by Django 5.2.1 on 2025-05-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('n_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('nacionalidade', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('nome_mae', models.CharField(blank=True, max_length=255)),
                ('nome_pai', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': '01. Funcionaros',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('n_registrofun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_ben', serialize=False, to='rh_app.funcionario')),
                ('nome_ben', models.CharField(max_length=255)),
                ('parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_ben', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '08. Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEstrangeiro',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_est', serialize=False, to='rh_app.funcionario')),
                ('rne', models.CharField(blank=True, max_length=14)),
                ('visto', models.CharField(blank=True, max_length=100)),
                ('numero_decreto', models.CharField(blank=True, max_length=20)),
                ('naturalidade', models.CharField(blank=True, max_length=50)),
                ('casado', models.BooleanField(default=False)),
                ('nome_conjuge', models.CharField(blank=True, max_length=255)),
                ('numero_filhos', models.IntegerField(blank=True)),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_est', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '05. Documentos estrangeiro',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFun',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_doc', serialize=False, to='rh_app.funcionario')),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('rg_orgao_emissor', models.CharField(blank=True, max_length=20)),
                ('rg_data_emissao', models.DateField(blank=True, null=True)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20)),
                ('titulo_zona', models.CharField(blank=True, max_length=10)),
                ('titulo_secao', models.CharField(blank=True, max_length=10)),
                ('ctps', models.CharField(blank=True, max_length=20)),
                ('ctps_serie', models.CharField(blank=True, max_length=20)),
                ('ctps_uf', models.CharField(blank=True, max_length=2)),
                ('ctps_data_emissao', models.DateField(blank=True, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20)),
                ('cnh_categoria', models.CharField(blank=True, max_length=5)),
                ('reservista', models.CharField(blank=True, max_length=20)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_doc', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '04. Documentos',
            },
        ),
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_em', serialize=False, to='rh_app.funcionario')),
                ('nome_emp', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('andar', models.CharField(blank=True, max_length=10)),
                ('apartamento', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_em', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '02. Empregadores',
            },
        ),
        migrations.CreateModel(
            name='FGTS',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_fgts', serialize=False, to='rh_app.funcionario')),
                ('banco_depositario', models.CharField(max_length=255)),
                ('data_opcao', models.DateField(blank=True, null=True)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_fgts', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '09. FGTS',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_func', serialize=False, to='rh_app.funcionario')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('hora_mes', models.TimeField(blank=True)),
                ('grau_instrucao', models.CharField(blank=True, max_length=50)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_pagamento', models.CharField(blank=True, max_length=100)),
                ('adic_insalubridade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adic_periculosidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_func', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '06. Funções',
            },
        ),
        migrations.CreateModel(
            name='HorarioTrab',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_hor', serialize=False, to='rh_app.funcionario')),
                ('dom', models.TimeField(blank=True)),
                ('seg', models.TimeField(blank=True)),
                ('ter', models.TimeField(blank=True)),
                ('qua', models.TimeField(blank=True)),
                ('qui', models.TimeField(blank=True)),
                ('sex', models.TimeField(blank=True)),
                ('sab', models.TimeField(blank=True)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_hor', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '07. Horarios',
            },
        ),
        migrations.CreateModel(
            name='PIS',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_pis', serialize=False, to='rh_app.funcionario')),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('cadatrado', models.DateField(blank=True, null=True)),
                ('nome_banco', models.CharField(blank=True, max_length=255)),
                ('endereco_banco', models.CharField(blank=True, max_length=255)),
                ('numero_banco', models.CharField(blank=True, max_length=10)),
                ('agencia', models.CharField(blank=True, max_length=50)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_pis', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '10. PIS',
            },
        ),
        migrations.CreateModel(
            name='Recisao',
            fields=[
                ('n_registrofun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_rec', serialize=False, to='rh_app.funcionario')),
                ('numero_homologacao', models.CharField(blank=True, max_length=100)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('tipo_desligamento', models.CharField(blank=True, max_length=100)),
                ('local_homologacao', models.CharField(blank=True, max_length=100)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_rec', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '11. Recisão',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('n_registrofun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registro_res', serialize=False, to='rh_app.funcionario')),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('andar', models.CharField(blank=True, max_length=10)),
                ('apartamento', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('nomefunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_res', to='rh_app.funcionario')),
            ],
            options={
                'verbose_name_plural': '03. Residencias',
            },
        ),
    ]
