# Generated by Django 5.2 on 2025-04-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_rh',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('SUPER', 'Super Administrador'), ('RH_ADMIN', 'Administrador RH'), ('RH', 'Usuário RH'), ('FUNC', 'Funcionário Comum')], default='FUNC', max_length=8),
        ),
    ]
