# Generated by Django 5.2 on 2025-04-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_app', '0002_remove_usuario_is_rh_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('estado_civil', models.CharField(blank=True, max_length=20)),
                ('nacionalidade', models.CharField(blank=True, max_length=50)),
                ('naturalidade', models.CharField(blank=True, max_length=50)),
                ('nome_mae', models.CharField(blank=True, max_length=255)),
                ('nome_pai', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('orgao_emissor', models.CharField(blank=True, max_length=20)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20)),
                ('zona', models.CharField(blank=True, max_length=10)),
                ('secao', models.CharField(blank=True, max_length=10)),
                ('reservista', models.CharField(blank=True, max_length=20)),
                ('ctps', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=20)),
                ('pis', models.CharField(blank=True, max_length=20)),
                ('cnh', models.CharField(blank=True, max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=5)),
                ('validade_cnh', models.DateField(blank=True, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=50)),
                ('curso', models.CharField(blank=True, max_length=100)),
                ('instituicao', models.CharField(blank=True, max_length=100)),
                ('conclusao', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
